// AUTO-GENERATED dataset for the catalog. Deterministic snapshot.
// In production this comes from Prisma (Product model). Regenerate via scripts/gen-catalog.
import type { CatalogProduct } from "@/types/catalog";

export const catalogProducts: CatalogProduct[] = [
  {
    "id": "p001",
    "slug": "kabeli-1-1",
    "title": "Кабель ВВГнг(А)-LS 2×1.5",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "Камкабель",
    "sku": "KAB-1001",
    "price": 273,
    "unit": "м",
    "availability": "in_stock",
    "material": "Медь",
    "cores": 2,
    "crossSection": 1.5,
    "voltage": 6,
    "createdAt": "2025-12-25",
    "popularity": 77,
    "badge": "Со склада"
  },
  {
    "id": "p002",
    "slug": "kabeli-2-2",
    "title": "Кабель АВВГ 2×2.5",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "Севкабель",
    "sku": "KAB-1002",
    "price": 375,
    "unit": "м",
    "availability": "in_stock",
    "material": "Алюминий",
    "cores": 2,
    "crossSection": 2.5,
    "voltage": 10,
    "createdAt": "2025-12-18",
    "popularity": 114
  },
  {
    "id": "p003",
    "slug": "kabeli-3-3",
    "title": "Кабель ВБбШв 2×4",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "Сарансккабель",
    "sku": "KAB-1003",
    "price": 191,
    "unit": "м",
    "availability": "on_order",
    "material": "Медь",
    "cores": 2,
    "crossSection": 4,
    "voltage": 0.66,
    "createdAt": "2025-12-11",
    "popularity": 11,
    "badge": "Новинка"
  },
  {
    "id": "p004",
    "slug": "kabeli-4-4",
    "title": "Кабель КГ 2×6",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "KazEnergoKabel",
    "sku": "KAB-1004",
    "price": 226,
    "unit": "м",
    "availability": "in_stock",
    "material": "Алюминий",
    "cores": 2,
    "crossSection": 6,
    "voltage": 1,
    "createdAt": "2025-12-04",
    "popularity": 88
  },
  {
    "id": "p005",
    "slug": "kabeli-5-5",
    "title": "Кабель ПвБбШп 2×10",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "Камкабель",
    "sku": "KAB-1005",
    "price": 392,
    "unit": "м",
    "availability": "in_stock",
    "material": "Медь",
    "cores": 2,
    "crossSection": 10,
    "voltage": 6,
    "createdAt": "2025-11-27",
    "popularity": 125,
    "badge": "Хит"
  },
  {
    "id": "p006",
    "slug": "kabeli-6-6",
    "title": "Кабель ВВГнг(А)-LS 2×16",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "Севкабель",
    "sku": "KAB-1006",
    "price": 564,
    "unit": "м",
    "availability": "on_order",
    "material": "Алюминий",
    "cores": 2,
    "crossSection": 16,
    "voltage": 10,
    "createdAt": "2025-11-20",
    "popularity": 22,
    "badge": "Со склада"
  },
  {
    "id": "p007",
    "slug": "kabeli-7-7",
    "title": "Кабель АВВГ 2×25",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "Сарансккабель",
    "sku": "KAB-1007",
    "price": 485,
    "unit": "м",
    "availability": "in_stock",
    "material": "Медь",
    "cores": 2,
    "crossSection": 25,
    "voltage": 0.66,
    "createdAt": "2025-11-13",
    "popularity": 99
  },
  {
    "id": "p008",
    "slug": "kabeli-8-8",
    "title": "Кабель ВБбШв 2×35",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "KazEnergoKabel",
    "sku": "KAB-1008",
    "price": 632,
    "unit": "м",
    "availability": "in_stock",
    "material": "Алюминий",
    "cores": 2,
    "crossSection": 35,
    "voltage": 1,
    "createdAt": "2025-11-06",
    "popularity": 136,
    "badge": "Новинка"
  },
  {
    "id": "p009",
    "slug": "kabeli-9-9",
    "title": "Кабель КГ 2×50",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "Камкабель",
    "sku": "KAB-1009",
    "price": 952,
    "unit": "м",
    "availability": "on_order",
    "material": "Медь",
    "cores": 2,
    "crossSection": 50,
    "voltage": 6,
    "createdAt": "2025-10-30",
    "popularity": 33
  },
  {
    "id": "p010",
    "slug": "kabeli-10-10",
    "title": "Кабель ПвБбШп 2×70",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "Севкабель",
    "sku": "KAB-1010",
    "price": 1320,
    "unit": "м",
    "availability": "in_stock",
    "material": "Алюминий",
    "cores": 2,
    "crossSection": 70,
    "voltage": 10,
    "createdAt": "2025-10-23",
    "popularity": 110,
    "badge": "Хит"
  },
  {
    "id": "p011",
    "slug": "kabeli-11-11",
    "title": "Кабель ВВГнг(А)-LS 3×1.5",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "Сарансккабель",
    "sku": "KAB-1011",
    "price": 163,
    "unit": "м",
    "availability": "in_stock",
    "material": "Медь",
    "cores": 3,
    "crossSection": 1.5,
    "voltage": 1,
    "createdAt": "2025-10-16",
    "popularity": 47,
    "badge": "Со склада"
  },
  {
    "id": "p012",
    "slug": "kabeli-12-12",
    "title": "Кабель АВВГ 3×2.5",
    "categorySlug": "kabeli",
    "category": "Кабели",
    "manufacturer": "KazEnergoKabel",
    "sku": "KAB-1012",
    "price": 287,
    "unit": "м",
    "availability": "on_order",
    "material": "Алюминий",
    "cores": 3,
    "crossSection": 2.5,
    "voltage": 6,
    "createdAt": "2025-10-09",
    "popularity": 44
  },
  {
    "id": "p013",
    "slug": "provoda-1-13",
    "title": "Провод СИП-2 1×1.5",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "ЭЛСИ",
    "sku": "PRO-1013",
    "price": 156,
    "unit": "м",
    "availability": "in_stock",
    "material": "Медь",
    "cores": 1,
    "crossSection": 1.5,
    "voltage": 0.66,
    "createdAt": "2025-10-02",
    "popularity": 121
  },
  {
    "id": "p014",
    "slug": "provoda-2-14",
    "title": "Провод ПуГВ 1×2.5",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "KazEnergoKabel",
    "sku": "PRO-1014",
    "price": 177,
    "unit": "м",
    "availability": "in_stock",
    "material": "Алюминий",
    "cores": 1,
    "crossSection": 2.5,
    "voltage": 1,
    "createdAt": "2025-09-25",
    "popularity": 58,
    "badge": "Новинка"
  },
  {
    "id": "p015",
    "slug": "provoda-3-15",
    "title": "Провод ПВС 1×4",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "Камкабель",
    "sku": "PRO-1015",
    "price": 185,
    "unit": "м",
    "availability": "on_order",
    "material": "Медь",
    "cores": 1,
    "crossSection": 4,
    "voltage": 0.4,
    "createdAt": "2025-09-18",
    "popularity": 55
  },
  {
    "id": "p016",
    "slug": "provoda-4-16",
    "title": "Провод ПВ-3 1×6",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "ЭЛСИ",
    "sku": "PRO-1016",
    "price": 219,
    "unit": "м",
    "availability": "in_stock",
    "material": "Алюминий",
    "cores": 1,
    "crossSection": 6,
    "voltage": 0.66,
    "createdAt": "2025-09-11",
    "popularity": 132,
    "badge": "Хит"
  },
  {
    "id": "p017",
    "slug": "provoda-5-17",
    "title": "Провод СИП-4 1×16",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "KazEnergoKabel",
    "sku": "PRO-1017",
    "price": 366,
    "unit": "м",
    "availability": "in_stock",
    "material": "Медь",
    "cores": 1,
    "crossSection": 16,
    "voltage": 1,
    "createdAt": "2025-09-04",
    "popularity": 69,
    "badge": "Со склада"
  },
  {
    "id": "p018",
    "slug": "provoda-6-18",
    "title": "Провод СИП-2 1×25",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "Камкабель",
    "sku": "PRO-1018",
    "price": 479,
    "unit": "м",
    "availability": "on_order",
    "material": "Алюминий",
    "cores": 1,
    "crossSection": 25,
    "voltage": 0.4,
    "createdAt": "2025-08-28",
    "popularity": 66
  },
  {
    "id": "p019",
    "slug": "provoda-7-19",
    "title": "Провод ПуГВ 1×35",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "ЭЛСИ",
    "sku": "PRO-1019",
    "price": 625,
    "unit": "м",
    "availability": "in_stock",
    "material": "Медь",
    "cores": 1,
    "crossSection": 35,
    "voltage": 0.66,
    "createdAt": "2025-08-21",
    "popularity": 43,
    "badge": "Новинка"
  },
  {
    "id": "p020",
    "slug": "provoda-8-20",
    "title": "Провод ПВС 1×70",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "KazEnergoKabel",
    "sku": "PRO-1020",
    "price": 1122,
    "unit": "м",
    "availability": "in_stock",
    "material": "Алюминий",
    "cores": 1,
    "crossSection": 70,
    "voltage": 1,
    "createdAt": "2025-08-14",
    "popularity": 80
  },
  {
    "id": "p021",
    "slug": "provoda-9-21",
    "title": "Провод ПВ-3 1×95",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "Камкабель",
    "sku": "PRO-1021",
    "price": 1459,
    "unit": "м",
    "availability": "on_order",
    "material": "Медь",
    "cores": 1,
    "crossSection": 95,
    "voltage": 0.4,
    "createdAt": "2025-08-07",
    "popularity": 77,
    "badge": "Хит"
  },
  {
    "id": "p022",
    "slug": "provoda-10-22",
    "title": "Провод СИП-4 2×1.5",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "ЭЛСИ",
    "sku": "PRO-1022",
    "price": 163,
    "unit": "м",
    "availability": "in_stock",
    "material": "Алюминий",
    "cores": 2,
    "crossSection": 1.5,
    "voltage": 1,
    "createdAt": "2025-07-31",
    "popularity": 54,
    "badge": "Со склада"
  },
  {
    "id": "p023",
    "slug": "provoda-11-23",
    "title": "Провод СИП-2 2×2.5",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "KazEnergoKabel",
    "sku": "PRO-1023",
    "price": 164,
    "unit": "м",
    "availability": "in_stock",
    "material": "Медь",
    "cores": 2,
    "crossSection": 2.5,
    "voltage": 0.4,
    "createdAt": "2025-07-24",
    "popularity": 91
  },
  {
    "id": "p024",
    "slug": "provoda-12-24",
    "title": "Провод ПуГВ 2×4",
    "categorySlug": "provoda",
    "category": "Провода",
    "manufacturer": "Камкабель",
    "sku": "PRO-1024",
    "price": 191,
    "unit": "м",
    "availability": "on_order",
    "material": "Алюминий",
    "cores": 2,
    "crossSection": 4,
    "voltage": 0.66,
    "createdAt": "2025-07-17",
    "popularity": 88,
    "badge": "Новинка"
  },
  {
    "id": "p025",
    "slug": "izolyatory-1-25",
    "title": "Изолятор ШС-6",
    "categorySlug": "izolyatory",
    "category": "Изоляторы",
    "manufacturer": "Ниcentr",
    "sku": "IZO-1025",
    "price": null,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Стекло",
    "cores": null,
    "crossSection": null,
    "voltage": 6,
    "createdAt": "2025-07-10",
    "popularity": 65,
    "badge": "Новинка"
  },
  {
    "id": "p026",
    "slug": "armatura-sip-1-26",
    "title": "Зажим анкерный ЗАБ 16",
    "categorySlug": "armatura-sip",
    "category": "Арматура СИП",
    "manufacturer": "ЭЛСИ",
    "sku": "ARM-1026",
    "price": 476,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": null,
    "crossSection": 16,
    "voltage": 0.4,
    "createdAt": "2025-07-03",
    "popularity": 102,
    "badge": "Со склада"
  },
  {
    "id": "p027",
    "slug": "armatura-sip-2-27",
    "title": "Зажим поддерживающий 25",
    "categorySlug": "armatura-sip",
    "category": "Арматура СИП",
    "manufacturer": "Ниled",
    "sku": "ARM-1027",
    "price": 530,
    "unit": "шт",
    "availability": "on_order",
    "material": "Сталь",
    "cores": null,
    "crossSection": 25,
    "voltage": 0.4,
    "createdAt": "2025-06-26",
    "popularity": 99
  },
  {
    "id": "p028",
    "slug": "armatura-sip-3-28",
    "title": "Ответвитель прокалывающий 35",
    "categorySlug": "armatura-sip",
    "category": "Арматура СИП",
    "manufacturer": "SICAME",
    "sku": "ARM-1028",
    "price": 590,
    "unit": "шт",
    "availability": "out",
    "material": "Пластик",
    "cores": null,
    "crossSection": 35,
    "voltage": 0.4,
    "createdAt": "2025-06-19",
    "popularity": 36,
    "badge": "Новинка"
  },
  {
    "id": "p029",
    "slug": "armatura-sip-4-29",
    "title": "Кронштейн анкерный 70",
    "categorySlug": "armatura-sip",
    "category": "Арматура СИП",
    "manufacturer": "ЭЛСИ",
    "sku": "ARM-1029",
    "price": 800,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Сталь",
    "cores": null,
    "crossSection": 70,
    "voltage": 0.4,
    "createdAt": "2025-06-12",
    "popularity": 113
  },
  {
    "id": "p030",
    "slug": "armatura-sip-5-30",
    "title": "Зажим анкерный ЗАБ 95",
    "categorySlug": "armatura-sip",
    "category": "Арматура СИП",
    "manufacturer": "Ниled",
    "sku": "ARM-1030",
    "price": 950,
    "unit": "шт",
    "availability": "on_order",
    "material": "Пластик",
    "cores": null,
    "crossSection": 95,
    "voltage": 0.4,
    "createdAt": "2025-06-05",
    "popularity": 10,
    "badge": "Хит"
  },
  {
    "id": "p031",
    "slug": "mufty-1-31",
    "title": "Муфта термоусаживаемая 3×16",
    "categorySlug": "mufty",
    "category": "Муфты",
    "manufacturer": "Райхем",
    "sku": "MUF-1031",
    "price": null,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": 3,
    "crossSection": 16,
    "voltage": 35,
    "createdAt": "2025-05-29",
    "popularity": 87,
    "badge": "Со склада"
  },
  {
    "id": "p032",
    "slug": "mufty-2-32",
    "title": "Муфта концевая 3×25",
    "categorySlug": "mufty",
    "category": "Муфты",
    "manufacturer": "КВТ",
    "sku": "MUF-1032",
    "price": 492,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": 3,
    "crossSection": 25,
    "voltage": 1,
    "createdAt": "2025-05-22",
    "popularity": 124
  },
  {
    "id": "p033",
    "slug": "mufty-3-33",
    "title": "Муфта соединительная 3×50",
    "categorySlug": "mufty",
    "category": "Муфты",
    "manufacturer": "3M",
    "sku": "MUF-1033",
    "price": 952,
    "unit": "шт",
    "availability": "on_order",
    "material": "Пластик",
    "cores": 3,
    "crossSection": 50,
    "voltage": 6,
    "createdAt": "2025-05-15",
    "popularity": 21,
    "badge": "Новинка"
  },
  {
    "id": "p034",
    "slug": "mufty-4-34",
    "title": "Муфта холодной усадки 3×70",
    "categorySlug": "mufty",
    "category": "Муфты",
    "manufacturer": "Райхем",
    "sku": "MUF-1034",
    "price": null,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": 3,
    "crossSection": 70,
    "voltage": 10,
    "createdAt": "2025-05-08",
    "popularity": 98
  },
  {
    "id": "p035",
    "slug": "mufty-5-35",
    "title": "Муфта термоусаживаемая 4×16",
    "categorySlug": "mufty",
    "category": "Муфты",
    "manufacturer": "КВТ",
    "sku": "MUF-1035",
    "price": 366,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": 4,
    "crossSection": 16,
    "voltage": 1,
    "createdAt": "2025-05-01",
    "popularity": 135,
    "badge": "Хит"
  },
  {
    "id": "p036",
    "slug": "mufty-6-36",
    "title": "Муфта концевая 4×25",
    "categorySlug": "mufty",
    "category": "Муфты",
    "manufacturer": "3M",
    "sku": "MUF-1036",
    "price": 602,
    "unit": "шт",
    "availability": "on_order",
    "material": "Пластик",
    "cores": 4,
    "crossSection": 25,
    "voltage": 6,
    "createdAt": "2025-04-24",
    "popularity": 32,
    "badge": "Со склада"
  },
  {
    "id": "p037",
    "slug": "mufty-7-37",
    "title": "Муфта соединительная 4×50",
    "categorySlug": "mufty",
    "category": "Муфты",
    "manufacturer": "Райхем",
    "sku": "MUF-1037",
    "price": null,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": 4,
    "crossSection": 50,
    "voltage": 10,
    "createdAt": "2025-04-17",
    "popularity": 109
  },
  {
    "id": "p038",
    "slug": "mufty-8-38",
    "title": "Муфта холодной усадки 4×70",
    "categorySlug": "mufty",
    "category": "Муфты",
    "manufacturer": "КВТ",
    "sku": "MUF-1038",
    "price": null,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": 4,
    "crossSection": 70,
    "voltage": 35,
    "createdAt": "2025-04-10",
    "popularity": 46,
    "badge": "Новинка"
  },
  {
    "id": "p039",
    "slug": "avtomaty-1-39",
    "title": "Автомат ВА47-29-0.4 C16",
    "categorySlug": "avtomaty",
    "category": "Автоматы",
    "manufacturer": "IEK",
    "sku": "AVT-1039",
    "price": 1960,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": 1,
    "crossSection": null,
    "voltage": 0.4,
    "createdAt": "2025-04-03",
    "popularity": 83,
    "badge": "Хит"
  },
  {
    "id": "p040",
    "slug": "avtomaty-2-40",
    "title": "Дифавтомат АД14-0.4 C25",
    "categorySlug": "avtomaty",
    "category": "Автоматы",
    "manufacturer": "EKF",
    "sku": "AVT-1040",
    "price": 1960,
    "unit": "шт",
    "availability": "on_order",
    "material": "Пластик",
    "cores": 2,
    "crossSection": null,
    "voltage": 0.4,
    "createdAt": "2025-03-27",
    "popularity": 80,
    "badge": "Со склада"
  },
  {
    "id": "p041",
    "slug": "avtomaty-3-41",
    "title": "УЗО ВД1-63-0.4 C32",
    "categorySlug": "avtomaty",
    "category": "Автоматы",
    "manufacturer": "КЭАЗ",
    "sku": "AVT-1041",
    "price": 1960,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": 3,
    "crossSection": null,
    "voltage": 0.4,
    "createdAt": "2025-03-20",
    "popularity": 57
  },
  {
    "id": "p042",
    "slug": "avtomaty-4-42",
    "title": "Выключатель нагрузки-0.4 C40",
    "categorySlug": "avtomaty",
    "category": "Автоматы",
    "manufacturer": "Schneider",
    "sku": "AVT-1042",
    "price": 1960,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Пластик",
    "cores": 4,
    "crossSection": null,
    "voltage": 0.4,
    "createdAt": "2025-03-13",
    "popularity": 94,
    "badge": "Новинка"
  },
  {
    "id": "p043",
    "slug": "vysokovoltnoe-1-43",
    "title": "Разъединитель РЛНД-10",
    "categorySlug": "vysokovoltnoe",
    "category": "Высоковольтное оборудование",
    "manufacturer": "ABB",
    "sku": "VYS-1043",
    "price": null,
    "unit": "шт",
    "availability": "in_stock",
    "material": "Сталь",
    "cores": null,
    "crossSection": null,
    "voltage": 10,
    "createdAt": "2025-12-31",
    "popularity": 131
  }
];

