/**
 * One-off migration: renames the ~43 seed/demo products' old
 * "<category>-<idx>-<counter>" slugs (e.g. "kabeli-1-1") to the new
 * title+SKU-based ones generated by scripts/gen-catalog.mjs, using the
 * static old→new map in src/config/slug-redirects.ts (that file is also
 * read at request time by /catalog/[slug] to 301 old links).
 *
 * Idempotent: only touches rows whose slug still matches an old value, so a
 * second run is a no-op. Requires DATABASE_URL to point at the target DB —
 * this repo's sandbox has no DB credentials, so this must be run from an
 * environment that does (e.g. `npm run db:deploy` first, then this script).
 *
 * Run: `npx tsx scripts/regenerate-demo-slugs.ts [--dry-run]`
 */
import { PrismaClient } from "@prisma/client";

import { slugRedirects } from "../src/config/slug-redirects";

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const prisma = new PrismaClient();

  let updated = 0;
  let skipped = 0;

  try {
    for (const [oldSlug, newSlug] of Object.entries(slugRedirects)) {
      const existing = await prisma.product.findUnique({
        where: { slug: oldSlug },
        select: { id: true, sku: true },
      });
      if (!existing) {
        skipped++;
        continue;
      }
      console.log(`${dryRun ? "[dry-run] " : ""}${oldSlug} -> ${newSlug} (sku ${existing.sku})`);
      if (!dryRun) {
        await prisma.product.update({ where: { id: existing.id }, data: { slug: newSlug } });
      }
      updated++;
    }
  } finally {
    await prisma.$disconnect();
  }

  console.log(
    `\n${dryRun ? "Would update" : "Updated"} ${updated} product(s); ${skipped} already renamed or not found.`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
