import type { Prisma } from "@prisma/client";

/** Real, checkable data-quality gaps — shared between the dashboard counters and the products list filter. */
export type ProductQualityFilter =
  "no-image" | "no-price" | "no-specs" | "no-description" | "template-description" | "no-documents";

export const QUALITY_FILTERS: ProductQualityFilter[] = [
  "no-image",
  "no-price",
  "no-specs",
  "no-description",
  "template-description",
  "no-documents",
];

export const QUALITY_FILTER_LABELS: Record<ProductQualityFilter, string> = {
  "no-image": "Без фото",
  "no-price": "Без цены",
  "no-specs": "Без характеристик",
  "no-description": "Без описания",
  "template-description": "Проверить шаблон описания",
  "no-documents": "Без документов",
};

export function qualityWhere(filter: ProductQualityFilter): Prisma.ProductWhereInput {
  switch (filter) {
    case "no-image":
      // Not just "zero image rows" — a product can have ProductImage rows
      // that are placeholders with no real url yet (e.g. freshly seeded
      // data), which should still count as missing a photo.
      return { images: { none: { AND: [{ url: { not: null } }, { NOT: { url: "" } }] } } };
    case "no-price":
      return { prices: { none: { kind: "BASE", amount: { not: null } } } };
    case "no-specs":
      return { values: { none: {} } };
    case "no-description":
      return { OR: [{ description: null }, { description: "" }] };
    case "template-description":
      // Candidate list for review. These phrases were generated by the old catalog seed;
      // a merchant may have edited surrounding copy, so avoid calling it an exact match.
      return {
        OR: [
          { description: { endsWith: "Уточните параметры и документы при запросе КП." } },
          {
            description: {
              contains:
                "AIMAG ELECTRIC обеспечивает подбор аналогов, расчёт под проект и доставку по всему Казахстану.",
            },
          },
        ],
      };
    case "no-documents":
      return { documents: { none: {} } };
  }
}
